### ISSUE TITLE
Onsen Style is not rendered on webpack5

### ISSUE THREAD

**Issue by yong-asial** [monaca-templates/onsenui-v2-angular2-tabbar#14]
@emccorson Hi Eric,
I'm trying to upgrade webpack to version 5 and it seems that the onsen style is not rendered. Maybe something wrong with the plugin of style loading. I noticed that you used to fix similar issue a few years back by adding `to-string-loader`. Maybe you are familiar with this issue than me.

You can check out the branch `dev_cordova11_webpack5` to reproduce the problem.

I also add `ignoreWarning` in webpack to ignore deprecated function in Angular --- not sure if it is the issue.

This is with warning when we run `npm run dev`
<img width="1411" alt="Screen Shot 2022-03-03 at 11 29 01" src="https://user-images.githubusercontent.com/28589278/156485685-ec67d0c4-30d6-4d01-9883-935a4a7140cc.png">

After ignore warning,
<img width="1281" alt="Screen Shot 2022-03-03 at 11 33 42" src="https://user-images.githubusercontent.com/28589278/156485727-413f9b3a-6150-47ef-bfe1-f7e8d579ff90.png">

As you can see in the console log warning, it seems not to render the styles properly

**Comment by yong-asial** [comment]
and this is error from opening the built file `www/index.html`
![Screen Shot 2022-03-03 at 11 45 02](https://user-images.githubusercontent.com/28589278/156486394-0af26118-bb30-471a-acad-f2d88aaeb808.png)

**Comment by emccorson** [comment]
Hi Yong,

I've created a PR that fixes the CSS styles. #15 

It looks like we don't need `to-string-loader` so I removed it. After that it seems the problem was the version of `style-loader` was too old so I bumped it to the latest version.

@yong-asial

**Comment by yong-asial** [comment]
@emccorson Thank you. It is working now!
